name: TurfWars
version: '${project.version}'
main: net.jadedmc.turfwars.TurfWars
depend: [JadedChat, PlaceholderAPI]

commands:
  admin:
    description: Admin command
  arena:
    description: Arena setup command.
    usage: /<command>
  play:
    description: Play command.
  spectate:
    description: Spectate a game.
    aliases: [spec]